#!/usr/bin/env python3
"""Regenerate data/catalog.js by scanning the subject folders for cheat sheets.

The landing page renders itself from that file, so adding a cheat sheet means
dropping an .html file into the right subject folder and running this script --
there is no list to hand-edit. The deploy workflow runs it on every push, and
the result is committed too so the site still works when opened from disk.

Each sheet supplies its own metadata through standard tags:

    <title>SQL — data-science-guide</title>
    <meta name="description" content="Joins, window functions, CTEs.">

Usage:
    python tools/build_catalog.py          # write data/catalog.js
    python tools/build_catalog.py --check  # exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "data" / "catalog.js"

# Order here is the order subjects appear on the landing page.
SUBJECTS: list[dict[str, str]] = [
    {
        "id": "data-science-overview",
        "title": "Data Science Overview",
        "blurb": "The shape of the field: workflow, roles, and how the pieces fit together.",
    },
    {
        "id": "probability-and-statistics",
        "title": "Probability and Statistics",
        "blurb": "Distributions, estimation, hypothesis testing, and inference.",
    },
    {
        "id": "python-programming",
        "title": "Python Programming",
        "blurb": "The language itself, plus the idioms that show up in analysis code.",
    },
    {
        "id": "data-analytics-tools",
        "title": "Data Analytics Tools",
        "blurb": "SQL, visualization libraries, notebooks, and the rest of the toolbox.",
    },
    {
        "id": "machine-learning-algorithms",
        "title": "Machine Learning Algorithms",
        "blurb": "Supervised and unsupervised methods, training, and evaluation.",
    },
    {
        "id": "big-data-principles",
        "title": "Big Data Principles",
        "blurb": "Distributed storage and compute, and what changes at scale.",
    },
    {
        "id": "deep-learning-methods",
        "title": "Deep Learning Methods",
        "blurb": "Neural architectures, training dynamics, and where each one applies.",
    },
]

TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S)
DESCRIPTION_RE = re.compile(
    r"""<meta\s[^>]*name=["']description["'][^>]*content=["'](.*?)["']""", re.I | re.S
)
H1_RE = re.compile(r"<h1[^>]*>(.*?)</h1>", re.I | re.S)
TAG_RE = re.compile(r"<[^>]+>")

# Sheets title themselves "<Topic> — data-science-guide"; keep only the topic.
TITLE_SEPARATORS = ("—", "–", "|", "·")


def clean(raw: str) -> str:
    """Strip tags and entities out of a captured fragment and collapse whitespace."""
    return re.sub(r"\s+", " ", html.unescape(TAG_RE.sub("", raw))).strip()


def topic_from_title(raw_title: str) -> str:
    text = clean(raw_title)
    for separator in TITLE_SEPARATORS:
        if separator in text:
            return text.split(separator)[0].strip()
    return text


def read_sheet(path: Path, subject_id: str) -> dict[str, str]:
    source = path.read_text(encoding="utf-8", errors="replace")

    title_match = TITLE_RE.search(source)
    heading_match = H1_RE.search(source)
    description_match = DESCRIPTION_RE.search(source)

    if title_match:
        title = topic_from_title(title_match.group(1))
    elif heading_match:
        title = clean(heading_match.group(1))
    else:
        title = path.stem.replace("-", " ").replace("_", " ").title()

    return {
        "title": title,
        "blurb": clean(description_match.group(1)) if description_match else "",
        "href": f"{subject_id}/{path.name}",
    }


def build() -> dict:
    subjects = []

    for subject in SUBJECTS:
        directory = ROOT / subject["id"]
        sheets = []

        if directory.is_dir():
            for path in sorted(directory.glob("*.html")):
                sheets.append(read_sheet(path, subject["id"]))
            sheets.sort(key=lambda sheet: sheet["title"].lower())

        subjects.append({**subject, "sheets": sheets})

    return {"subjects": subjects}


def render(catalog: dict) -> str:
    body = json.dumps(catalog, indent=2, ensure_ascii=False)
    return (
        "/* Generated by tools/build_catalog.py -- do not edit by hand.\n"
        "   Add a cheat sheet by dropping an .html file into its subject folder,\n"
        "   then re-run the script (the deploy workflow also runs it). */\n"
        f"window.DSG_CATALOG = {body};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if data/catalog.js is out of date instead of writing it",
    )
    args = parser.parse_args()

    catalog = build()
    rendered = render(catalog)

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print("data/catalog.js is stale -- run: python tools/build_catalog.py", file=sys.stderr)
            return 1
        print("data/catalog.js is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")

    total = sum(len(subject["sheets"]) for subject in catalog["subjects"])
    print(f"wrote {OUTPUT.relative_to(ROOT).as_posix()} ({total} sheet(s))")
    for subject in catalog["subjects"]:
        names = ", ".join(sheet["title"] for sheet in subject["sheets"]) or "-"
        print(f"  {subject['id']:<32} {names}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
